#---------------------------------------------------------------------
# Many thanks Denis Astahov(c) 2019
#---------------------------------------------------------------------
name: hub-act
env:
  APPLICATION_NAME    : "prod_app"
  DEPLOY_PACKAGE_NAME : "ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - master

jobs:
  my_master:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello World from Testing job"
    
    - name: Execure few commands
      run : |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Appication name: ${{ env.APPLICATION_NAME }}"
